/Users/bgamari/bin-dist-7.10.3b-Darwin/ghc/inplace/lib/bin/haddock -B/Users/bgamari/bin-dist-7.10.3b-Darwin/ghc/inplace/lib -l/Users/bgamari/bin-dist-7.10.3b-Darwin/ghc/inplace/lib --odir=libraries/binary/dist-install/doc/html/binary --no-tmp-comp-dir --dump-interface=libraries/binary/dist-install/doc/html/binary/binary.haddock --html --hoogle --title=binary-0.7.5.0: Binary serialisation for Haskell values using lazy ByteStrings --prologue=libraries/binary/dist-install/haddock-prologue.txt --hide=Data.Binary.Builder.Base --hide=Data.Binary.Class --hide=Data.Binary.Generic --read-interface=../array-0.5.1.0,../array-0.5.1.0/src/%{MODULE/./-}.html#%{NAME},libraries/array/dist-install/doc/html/array/array.haddock --read-interface=../base-4.8.2.0,../base-4.8.2.0/src/%{MODULE/./-}.html#%{NAME},libraries/base/dist-install/doc/html/base/base.haddock --read-interface=../bytestring-0.10.6.0,../bytestring-0.10.6.0/src/%{MODULE/./-}.html#%{NAME},libraries/bytestring/dist-install/doc/html/bytestring/bytestring.haddock --read-interface=../containers-0.5.6.2,../containers-0.5.6.2/src/%{MODULE/./-}.html#%{NAME},libraries/containers/dist-install/doc/html/containers/containers.haddock --optghc=-hisuf --optghc=dyn_hi --optghc=-osuf --optghc=dyn_o --optghc=-hcsuf --optghc=dyn_hc --optghc=-fPIC --optghc=-dynamic --optghc=-H32m --optghc=-O --optghc=-this-package-key --optghc=binar_3uXFWMoAGBg0xKP9MHKRwi --optghc=-hide-all-packages --optghc=-i --optghc=-ilibraries/binary/src --optghc=-ilibraries/binary/dist-install/build --optghc=-ilibraries/binary/dist-install/build/autogen --optghc=-Ilibraries/binary/dist-install/build --optghc=-Ilibraries/binary/dist-install/build/autogen --optghc=-Ilibraries/binary/. --optghc=-optP-DGENERICS --optghc=-optP-include --optghc=-optPlibraries/binary/dist-install/build/autogen/cabal_macros.h --optghc=-package-key --optghc=array_67iodizgJQIIxYVTp4emlA --optghc=-package-key --optghc=base_HQfYBxpPvuw8OunzQu6JGM --optghc=-package-key --optghc=bytes_6VWy06pWzJq9evDvK2d4w6 --optghc=-package-key --optghc=conta_2C3ZI8RgPO2LBMidXKTvIU --optghc=-O2 --optghc=-Wall --optghc=-fliberate-case-threshold=1000 --optghc=-XHaskell98 --optghc=-O2 --optghc=-no-user-package-db --optghc=-rtsopts --optghc=-odir --optghc=libraries/binary/dist-install/build --optghc=-hidir --optghc=libraries/binary/dist-install/build --optghc=-stubdir --optghc=libraries/binary/dist-install/build --source-module=src/%{MODULE/./-}.html --source-entity=src/%{MODULE/./-}.html#%{NAME} libraries/binary/src/Data/Binary.hs libraries/binary/src/Data/Binary/Put.hs libraries/binary/src/Data/Binary/Get.hs libraries/binary/src/Data/Binary/Get/Internal.hs libraries/binary/src/Data/Binary/Builder.hs libraries/binary/src/Data/Binary/Builder/Internal.hs libraries/binary/src/Data/Binary/Builder/Base.hs libraries/binary/src/Data/Binary/Class.hs libraries/binary/src/Data/Binary/Generic.hs +RTS -tlibraries/binary/dist-install/doc/html/binary/binary.haddock.t --machine-readable 
 [("bytes allocated", "777538424")
 ,("num_GCs", "1113")
 ,("average_bytes_used", "22202517")
 ,("max_bytes_used", "58777672")
 ,("num_byte_usage_samples", "7")
 ,("peak_megabytes_allocated", "125")
 ,("init_cpu_seconds", "0.000")
 ,("init_wall_seconds", "0.001")
 ,("mutator_cpu_seconds", "0.383")
 ,("mutator_wall_seconds", "0.569")
 ,("GC_cpu_seconds", "0.473")
 ,("GC_wall_seconds", "0.511")
 ]
